trojsten/events/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.event_list, {'path': '/akcie'}, name='event_list'),
    url(r'^sustredenia/$', views.camp_event_list, {'path': '/akcie/sustredenia', }, name='camp_event_list'),
    url(r'^(?P<event_id>(\d+))/$',
        views.event_detail, name='event_detail'),
    url(r'^(?P<event_id>(\d+))/zoznam_ucastnikov/$',
        views.participants_organizers_list, name='participants_list'),
]

trojsten/special/plugin_ksp_32_1_1/urls.py
from django.conf.urls import url

from trojsten.special.plugin_ksp_32_1_1 import views

app_name = 'plugin_zwarte'

urlpatterns = [
    url(r'^$', views.main),
    url(r'^level/(?P<level>\d+)/', views.main, name="main"),
    url(r'^run/(?P<level>\d+)/', views.run, name="run"),
]

trojsten/special/plugin_ksp_32_1_1/models.py
from django.conf import settings
from django.db import models


class UserLevel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+', on_delete=models.CASCADE)
    level_id = models.IntegerField()
    try_count = models.IntegerField(default=0)
    solved = models.BooleanField(default=False)

    MAX_TRY_COUNT = 50

    def add_try(self, input, output):
        self.try_count += 1
        self.save()
        new_try = Try(userlevel=self, input=str(input), output=str(output))
        new_try.save()
        if self.try_count > UserLevel.MAX_TRY_COUNT:
            self.try_set.order_by('id')[0].delete()

    class Meta:
        unique_together = (("user", "level_id"),)


class Try(models.Model):
    userlevel = models.ForeignKey('UserLevel', on_delete=models.CASCADE)
    input = models.CharField(max_length=15)
    output = models.CharField(max_length=40)

trojsten/special/plugin_ksp_32_1_1/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.urls import reverse

from .core import LEVELS
from .models import UserLevel
from .update_points import update_points


@login_required()
def main(request, level=1):
    level = max(min(int(level), 10), 1)
    user = request.user
    userlevel, _ = UserLevel.objects.get_or_create(level_id=level, user=user)

    target = str(LEVELS[level].TARGET)

    try_set = []
    for x in userlevel.try_set.order_by('id'):
        try_set.append((x.input, x.output, x.output == target))

    levels = [[i, False] for i in range(1, 11)]
    for x in UserLevel.objects.filter(user=user):
        levels[x.level_id - 1][1] = x.solved

    return render(request, 'plugin_ksp_32_1_1/level.html', {
        "level": level,
        "levels": levels,
        "solved": userlevel.solved,
        "target": target,
        "try_set": try_set,
        "try_count": userlevel.try_count,
        "try_count_ending":
        {1: '', 2: 'y', 3: 'y', 4: 'y'}.get(userlevel.try_count, 'ov'),
    })


@login_required()
def run(request, level=1):
    level = max(min(int(level), 10), 1)
    user = request.user
    userlevel, _ = UserLevel.objects.get_or_create(level_id=level, user=user)

    try:
        data = json.loads(request.read().decode("utf-8"))
        _input = str(int(data["input"]))
    except (KeyError, ValueError):
        return HttpResponseBadRequest()

    _output = LEVELS[level].run(_input)

    solved = _output == LEVELS[level].TARGET
    solved_right_now = solved and not userlevel.solved

    if not userlevel.solved:
        userlevel.add_try(_input, str(_output))

    if solved_right_now:
        userlevel.solved = True
        userlevel.save()
        update_points(user)

    return HttpResponse(
        json.dumps({
            "level": level,
            "input": str(_input),
            "output": _output,
            "solved": solved,
            "refresh": solved_right_now,
            "try_count": userlevel.try_count,
            "next_url": reverse('plugin_zwarte:run', args=(level,),
                                current_app=request.resolver_match.namespace)
        }),
        content_type="application/json",
    )

trojsten/special/plugin_ksp_32_1_1/templates/plugin_ksp_32_1_1/level.html
<!DOCTYPE html>
{% load staticfiles %}

<!--suppress XmlDuplicatedId -->
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Zwarte doos</title>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="{% static "plugin_ksp_32_1_1/cover.css" %}" rel="stylesheet">
  <link href='{% static "plugin_ksp_32_1_1/zwarte.css" %}' rel="stylesheet">

  <style id="holderjs-style" type="text/css"></style>

</head>
<body>

  <div class="site-wrapper">

    <div class="site-wrapper-inner">

      <div class="cover-container">

        <div class="masthead clearfix">
          <div class="inner">
            <h3 class="masthead-brand">Zwarte Doos</h3>
            <ul class="nav masthead-nav">
              {% for lvl, solved in levels %}
                <li class='{% if lvl == level %}active{% endif %}'>
                  <a href='{% url "plugin_zwarte:main" lvl %}'>
                    {% if solved %}
                      {{lvl}}&#10003;
                    {% else %}
                      &nbsp;{{lvl}}&nbsp;
                    {% endif %}
                  </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>

        <div class="inner cover">
          <h1 class="cover-heading">Level {{level}}</h1>
          {% if solved %}
              <p class="lead">
                  Gratulujeme!<br/>
                  Dosiahol si <code class="solved">{{target}}</code>
                  na <span id="try-count">{{try_count}}</span>
                  pokus{{try_count_ending}}.
              </p>
          {% else %}
              <p class="lead">
                  Dosiahni <code class="solved">{{target}}</code><br/>
                  Zatiaľ si mal(a) <span id="try-count">{{try_count}}</span>
                  pokusov.
              </p>
          {% endif %}

          <form class="form-inline" role="form" id="valueForm">
            {% csrf_token %}
            <div class="form-group">
              <label class="sr-only" for="value">Zadaj číslo</label>
              <input
                      type="number"
                      min="0"
                      max="9999999999"
                      class="form-control"
                      id="value"
                      placeholder="Zadaj číslo"
              >
            </div>
            <button type="submit" class="btn btn-default">Pošli</button>
          </form>


          <div class="results">
            <table id = 'resultsTable'>
            </table>
          </div>

        </div>

        <div class="mastfoot">
          <div class="inner">
            <p>&copy; KSP 2014</p>
          </div>
        </div>

      </div>

    </div>

  </div>

<!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
  <script src='{% static "plugin_ksp_32_1_1/send.js" %}'></script>
  <script type="text/javascript">
    window.submit_url="{% url "plugin_zwarte:run" level %}";
  </script>
  <script type="text/javascript">
    {% for input, output, solved in try_set %}
        window.add_row("{{input}}","{{output}}",{{solved|yesno:"true,false"}});
    {% endfor %}
  </script>
  <script src='{% static "js/bootstrap.min.js" %}'></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src='{% static "plugin_ksp_32_1_1/ie10-viewport-bug-workaround.js" %}'></script>


</body>
</html>